'use client';
import { useState, useEffect } from 'react';
export default function GoalCard({ goal, onDelete, onUpdate }: any){
  const [showEdit, setShowEdit] = useState(false);
  const [local, setLocal] = useState(goal);
  const calcTimeProgress = (g:any)=>{ try{ const start = new Date(g.createdAt || Date.now()).getTime(); const end = new Date(g.deadline).getTime(); if (isNaN(end)) return 0; const total = end - start; const passed = Date.now() - start; const pct = Math.max(0, Math.min(100, Math.round((passed/total)*100))); return pct;}catch(e){return 0;} };
  const [timePct,setTimePct]=useState(calcTimeProgress(local));
  useEffect(()=>{ const t=setInterval(()=> setTimePct(calcTimeProgress(local)),5000); return ()=>clearInterval(t); },[local]);
  const complete=()=>{ const u={...local,status:'completed',progress:100}; setLocal(u); onUpdate && onUpdate(u); alert('Marked complete (demo)') };
  const forfeit=()=>{ if(!confirm('Forfeit and lose 25%?')) return; const penalty=(local.stakeAmount||local.stake||0)*0.25; const u={...local,status:'forfeited'}; setLocal(u); onUpdate && onUpdate(u); alert('Forfeited — penalty £'+penalty.toFixed(2)); };
  const save=()=>{ onUpdate && onUpdate(local); setShowEdit(false); };
  const progressColor = timePct>80 ? 'linear-gradient(90deg,#f97316,#ef4444)' : (timePct>50? 'linear-gradient(90deg,#facc15,#fb923c)' : 'linear-gradient(90deg,#34d399,#10b981)');
  return (<div className="goal card"><div style={{display:'flex',justifyContent:'space-between'}}><strong>{local.title}</strong><div style={{color:'var(--muted)'}}>£{local.stakeAmount||local.stake||0}</div></div><div style={{color:'var(--muted)'}}>{local.description||local.desc}</div><div style={{marginTop:8,fontSize:13}} className="muted">Deadline: {local.deadline||'—'} • {local.hasValidator? 'Validator':'Solo'} {local.validatorEmail? '• '+local.validatorEmail : ''}</div><div className="progress" style={{marginTop:10}}><i style={{width:`${timePct}%`, background:progressColor}}></i></div><div style={{display:'flex',gap:8,marginTop:8,flexWrap:'wrap'}}><button className="btn" onClick={complete}>Complete</button><button className="btn ghost" onClick={forfeit}>Forfeit</button><button className="btn ghost" onClick={()=>setShowEdit(s=>!s)}>{showEdit? 'Close':'Edit'}</button><button className="btn ghost" onClick={onDelete}>Delete</button></div>{showEdit && <div style={{marginTop:8}}><input className="input" value={local.title} onChange={e=>setLocal({...local,title:e.target.value})} /><input className="input" value={local.description||local.desc} onChange={e=>setLocal({...local,description:e.target.value})} /><input className="input" type="date" value={local.deadline} onChange={e=>setLocal({...local,deadline:e.target.value})} /><div style={{display:'flex',gap:8,marginTop:8}}><button className="btn" onClick={save}>Save</button></div></div>}</div>) }
